name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a dummy change
        run: |
          echo "Last run: $(date)" > last-run.txt

      - name: Commit changes
        run: |
          git config --global user.name 'Raushan Kumar'
          git config --global user.email 'raushforlife@gmail.com'
          git add last-run.txt
          git commit -m "Daily commit: $(date)"
          git push
