name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: echo "$(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name 'raushgit'
          git config --global user.email 'raushforlife@gmail.com'
          git add .
          git commit -m "Daily update"
          git push
